// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAveDnX0fgHjkJlJR5Rlxhr_99U8__AkPE',
    appId: '1:159823242073:web:07ef8170af3f0ecf492248',
    messagingSenderId: '159823242073',
    projectId: 'caulapool',
    authDomain: 'caulapool.firebaseapp.com',
    storageBucket: 'caulapool.appspot.com',
    measurementId: 'G-459SPH584D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzFF2prXsOymX_ICqFUNhD9f8E_cd3kaw',
    appId: '1:159823242073:android:9e460309d371d31f492248',
    messagingSenderId: '159823242073',
    projectId: 'caulapool',
    storageBucket: 'caulapool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKhDhpTOKeSFYyyAwkE8WQSzZk4vNwjM',
    appId: '1:159823242073:ios:c68ba31556402555492248',
    messagingSenderId: '159823242073',
    projectId: 'caulapool',
    storageBucket: 'caulapool.appspot.com',
    iosBundleId: 'com.example.ssss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIKhDhpTOKeSFYyyAwkE8WQSzZk4vNwjM',
    appId: '1:159823242073:ios:16d66b2db05db585492248',
    messagingSenderId: '159823242073',
    projectId: 'caulapool',
    storageBucket: 'caulapool.appspot.com',
    iosBundleId: 'com.example.ssss.RunnerTests',
  );
}
